name: chartgpt-ui-docker CI

# 在master分支发生push事件时触发。
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#env: # 设置环境变量
#  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）
#  WORK_DIR: chartgpt-ui-docker #工作目录
#
#defaults:
#  run:
#    shell: bash
#    working-directory: chartgpt-ui-docker

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag chartgpt-ui-docker:${{ github.sha }}

      - name: Log in to AliYun
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-beijing.aliyuncs.com # 登录阿里云镜像仓库

      - name: Push the Docker image
        id: build_image
        #        run: docker push myapp:${{ github.sha }}
        run: |
#          echo "::set-output name=image_id::$(docker images --filter=reference='chartgpt-ui-docker:${{ github.sha }}' --format='{{.ID}}')"
          echo "image_id=$(docker images --filter=reference='chartgpt-ui-docker:${{ github.sha }}' --format='{{.ID}}')" >> $GITHUB_OUTPUT
          docker tag ${{ steps.build_image.outputs.image_id }} registry.cn-beijing.aliyuncs.com/f-chatgpt-web/chatgpt-web:${{ github.sha }}
          docker push registry.cn-beijing.aliyuncs.com/f-chatgpt-web/chatgpt-web:${{ github.sha }}

