name: chartgpt-ui-docker CI

# 在master分支发生push事件时触发。
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#env: # 设置环境变量
#  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）
#  WORK_DIR: chartgpt-ui-docker #工作目录
#
#defaults:
#  run:
#    shell: bash
#    working-directory: chartgpt-ui-docker

env:
  MY_VAR: registry.cn-beijing.aliyuncs.com/f-chatgpt-web/chatgpt-web
  DOCKER_CONTAINER_NAME: chartgpt-ui-docker

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $MY_VAR:${{ github.sha }}

      - name: Log in to AliYun
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-beijing.aliyuncs.com # 登录阿里云镜像仓库

      - name: Push the Docker image
        run: docker push $MY_VAR:${{ github.sha }}

      - name: Deploy To Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 60s
          script: |
            docker pull $MY_VAR:${{ github.sha }}
            docker rm -f chartgpt-ui-docker
            docker run --name $DOCKER_CONTAINER_NAME -it -d -p 8080:8080 $MY_VAR:${{ github.sha }}
            exit