name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@master
        with:
          java-version: 11
          distribution: "adopt"
          cache: maven
      - run: |
          mvn clean package -DskipTests --file pom.xml
          ls -l
          ls -l target
      - name: copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "target/chartgpt-service.jar"
          debug: true #开启调试
          # rm: true
          target: "/home"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 20s
          debug: true #开启调试
          script: |
            cd /home/target
            ps -ef | grep chartgpt-service.jar | grep -v grep | awk '{print $2}' | xargs kill -9
            nohup java -jar chartgpt-service.jar > nohup.out &
            pwd
            exit
